accepted = ["MIT", "Apache-2.0", "ISC", "BSD-3-Clause", "MPL-2.0", "Unicode-3.0", "Zlib", "BSL-1.0"]
targets = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-pc-windows-msvc"]
ignore-dev-dependencies = true
